### ISSUE TITLE
Feature Request!

### ISSUE THREAD

**Issue by Jokelass** [RagedUnicorn/wow-classic-gearmenu#1]
Hello!

First off I'd just like to express my thanks to you for creating this addon. Playing vanilla without ItemRack (seeing as the Author of that has no plans to update for Classic) would be awful and this seems to have similar functionality! Great. However I believe there are things that could make this addon even greater than the Original ItemRack.

As I am sure you're aware there's also another similar addon called TrinketMenu which is an essential tool in most vanilla player's toolkit by now. But why stop there? TrinketMenu is and has always been more powerful than ItemRack an any other addon of similar nature but I've never quite understood why. With my limited knowledge of programming. Shouldn't the TrinketMenu features such as Queueing trinkets automatically be very easy to just copy & paste to other slots such as boots?

The way this works with Trinkets is amazing and without this feature it's eating up a lot of my keybinds for no apparent reason. Let me explain how this works and why it is so good.

Let's say you have your PvP Trinket and your Tidal Charm equipped on your hunter. You're running about having a great time in PvP. If you have TrinketMenu enabled and setup in a certain way then what will happen when you use your PvP Trinket is that it'll automatically queue up the next trinket of your choice (Usually your stat trinket seeing as equipping another on-use trinket will put it on a 30s cooldown). So for simplicity's sake let's say it automatically queues up your Blackhand's Breadth (2% crit). The next time I use Feign Death it'll automatically and simply equip that trinket instead of the PvP Trinket without any interaction from me (freeing up a use of a keybind mid combat for me). Then when PvP Trinket is back off cooldown it'll queue that back up again.

However I believe this is even better for engineering items that you want to use. Because of the huge variety of trinkets there are in the game it is impractical to have these queues. You will want different trinkets all the time. However, with for example rocket boots. You will want them equipped most of the time to make sure you're ready to go at any time. When this item goes on cooldown you basically always want to swap to your normal boots.

Great feature, extremely underrated and never ever ported to other slots than Trinkets.

I realise this feature is probably asking a lot and there's tonne of small things that could make this truly great. I hope we see this from you sometime down the line.

Good Luck and Thanks! I hope you consider what I have had to say.

**Comment by RagedUnicorn** [comment]
Hi @Jokelass,

Thanks for taking your time to write. Always glad to hear that people find the addon useful.

TrinketMenu was definitely my inspiration when I started working on this addon. I'm not sure if you saw that I originally wrote the GearMenu addon for vanilla wow. 

You can find the repository here:
https://github.com/RagedUnicorn/wow-vanilla-gearmenu

I fully agree with your described usecase of wanting to switch to another item once it is used and I think GearMenu already supports what you described. For know you can have a look at the vanilla repository and search for 'Quick Change'. From what I read this fulfils what you described.

- On the left side you have to choose an item that has an 'onUse' effect such as the rocket bots.
- On the right side you choose the item that you want to equip after using the left side item.
- You can additionally (and should) set a delay to wait for until the item is switched. This is because if you switch the rocket bots you will instantly loose the speed buff again. So you would usually set that delay to the duration of the onUse effect. I couldn't find a way to programatically get that duration automatically. So for the rockets boots you would set it to 20 seconds. https://classic.wowhead.com/item=10724/gnomish-rocket-boots

Afterwards this is considered as a quickchange rule. GearMenu monitors your combat log and compares certain actions with the defined rules. If one matches the rule takes effect. In this case it would add your other boots into the 'combat queue' and switch them as soon as possible.

I had to rewrite the addon almost from the ground up because a lot changed since then. The addon itself is currently considered done in regards of development tasks. I have no open points currently that I need to work on. I was however not really able to test a lot. I had no access to the classic beta and was only able to check some very basic things in the last stresstest (and even found a bug that I was able to fix). I did however lack important items to actually fully test the addon. I dislike releasing an untested version of the addon because I have some claims to a certain quality of a release.

This means however that interested people with some technical understanding can already download the master branch of the addon (name the folder GearMenu) and change some basic values in the `GM_Environment.lua` file (to stop the debug log spam).

Copy and overwrite the content of the file with the following:

```lua
RGGM_ENVIRONMENT = {
  ADDON_IDENTIFIER = "com.ragedunicorn.wow.classic.gearmenu-addon",
  LOG_LEVEL = 1,
  LOG_EVENT = false,
  DEBUG = false
}
```

No guarantees that everything will work fine but feel free to create an issue here if you find something.

Next steps for the addon are:
- Proper Testing once I have a character with certain engineering and similar items
- Update the readme with proper gifs that explain the features
- Look into releasing the addon via twitch/curse

Cheers,
RagedUnicorn
