### ISSUE TITLE
Tabard Slot

### ISSUE THREAD

**Issue by Goatella** [RagedUnicorn/wow-classic-gearmenu#10]
Not so much an issues as a request... it would be nice if the Tabard slot was included, for in town pretty sets :)

Shirt too actually!

And the ability to toggle a slot to be empty

**Comment by RagedUnicorn** [comment]
Hi @Goatella,

Sorry I don't plan to include that slot because I really don't see any use in it. I think for an in town set Outfitter or similar addons are mor suited to that. This addon aims mainly to support slots that have an onuse effect and then switch to something else after using it.

I'm not sure about your last comment about the empty slot. It is currently possible to deactivate every slot that you don't want to use. See the standard addons interface options for details on what slots can be activated or deactivated.

Cheers,
RagedUnicorn
