### ISSUE TITLE
No issues, just a few suggestions.

### ISSUE THREAD

**Issue by AGandrup** [RagedUnicorn/wow-classic-gearmenu#18]
Heya man, great addon! I like it a lot. 

I have a few suggestions/request which I hope you'll consider adding at some point.

First of all I'd really like an option to scale the size of the icons. I'd also like an option to seperate the icons for example so I can have my trinket icons at one place on the screen while having the icons for my other gear somewhere else (hope that makes sense).
Next, I'd like an option to make the bar/rows go vertical instead of horizontal only. And last but not least I'd love if you could make and option to have items always shown (like instead of having to hover over).

I suppose this would require a lot of time to develop and implement but I hope you will consider it at the very least :-) 

Anyway, keep up the good work.
Let me know if any of what I just wrote doesn't make any sense and I'll try to explain better.

Cheers.

**Comment by RagedUnicorn** [comment]
Hi @AGandrup 

Thanks good to hear you like the addon!

* The scalling of buttons is definitely on my todo list and will be in one of the next versions
* Having slots in different positions seems a bit harder todo. I will have a look at it but not with the biggest priority
* Vertical/Horizontal bars - This is definitely a feature that should be doable. Just a bit of work because you then also need to be able to configure on which side the changeMenu is displayed when you hover over the slot
* Always showing items - I think I understand what you mean by this. I saw that the old trinketmenu supported this. I do however not know how this should look for GearMenu. It would mean that the changeMenu could only be 1 row thick and grow upwards. I think that would get quite cluttered for most people. I think I will experiment with it a bit when I find the time.

Cheers,
RagedUnicorn

**Comment by Zonzei** [comment]
I have few requests/suggestions as well and since some of them are similar or same as the ones here I don't feel like new thread is warranted. 

1. Option to choose between vertical/horizontal bar as well as the direction of flyout menu (or changeMenu as you seem to call it).
2. Option to hide out of combat and override Keybind/modifier to show the bar regardless of being out of combat (for me it would be hold alt > show).
3. [Masque](https://github.com/StormFX/Masque/wiki/Masque-API) support or at least ability to hide/change the border width and spacing.
4. Show numerical cooldown (added by OmniCC) but hide the cooldown sweep.

![example](https://user-images.githubusercontent.com/28210225/68096184-b6bfbc80-feb7-11e9-889c-1d54cbd02916.png)

Otherwise great addon but these few appearance _issues_ kinda clash with rest of my UI.

**Comment by Altarus94** [comment]
I'll use this post for request then !

- Vertical/Horizontal bars => This is a must, live to heard that it's on your to do !
- Change the side the flyout menu show up, right now, you con't use gear menu place on top of the screen.
- It would be awesome if you can make multiple row if you need to chow a very large number of slots, or maybe a button to switch between multiple slots.

Love the addon, good luck !

**Comment by ollema** [comment]
@RagedUnicorn it's better to bump this old issue instead of creating a new one right?

I really enjoy this addon - however there is some features missing from TrinketMenu that's preventing me to switch completely to this addon.

Mainly, the ability to always show items in the changeMenu and for the changeMenu to grow vertically (these two goes hand in hand).

Here is an example of my setup with TrinketMenu and GearMenu:
![3fb73bcbe8272797990110951f1467e3](https://user-images.githubusercontent.com/31876997/79569343-b73fbe80-80b7-11ea-97ae-477c2ed9cda5.png)
As you can see, I have my currently equipped trinkets at the top, and then the rest of the trinkets shown below.

Having all the trinkets always shown allows me to switch faster because I don't have to mouse over and look for the correct trinket.

---

The second, less important feature missing is Masque support.

As seen in this screenshot:
![781a22959b288d3ce8349b078edb448d](https://user-images.githubusercontent.com/31876997/79569556-169dce80-80b8-11ea-9061-673a2988d689.jpg)
I use Masque for my action bar. I would be very nice if GearMenu was skinned with Masque as well!

I believe this issue is tracked in https://github.com/RagedUnicorn/wow-classic-gearmenu/issues/50 - I just wanted to share a screenshot and voice my support for this issue!

**Comment by RagedUnicorn** [comment]
Cleanup - Closing this
