### ISSUE TITLE
Can't hide or resize window

### ISSUE THREAD

**Issue by alecjpav** [RagedUnicorn/wow-classic-gearmenu#2]
Hello, thank you for this addon! For some reason the window is huge, it takes up over half my screen's width. I can't figure out how to resize the window or at least hide it when I don't need out. Is there any way to do this? Thanks!

**Comment by RagedUnicorn** [comment]
Hi there,

Didn't see that happen on the stresstest but there might be a problem with the scale. It is currently not possible to scale or hide the window. Can you attach a screenshot how it looks for you? I'm currently busy leveling :D but will start looking into the addon once I hit 60.

Cheers,
RagedUnicorn

**Comment by Road-block** [comment]
For early adopters, to scale the bar do something like this

Add under [GM_Constants.lua#L89](https://github.com/RagedUnicorn/wow-classic-gearmenu/blob/master/code/GM_Constants.lua#L89)
```lua
ELEMENT_GEAR_BAR_SCALE = 0.7, -- your preferred scale here
```
Then under [gui/GM_GearBar.lua#L51](https://github.com/RagedUnicorn/wow-classic-gearmenu/blob/master/gui/GM_GearBar.lua#L51)
```lua
gearBarFrame:SetScale(RGGM_CONSTANTS.ELEMENT_GEAR_BAR_SCALE)
```
You'll have to remember to re-apply your edits for updates (until something is put into the mainline)

**Comment by RagedUnicorn** [comment]
Hi @alecjpav,

This was fixed with commit https://github.com/RagedUnicorn/wow-classic-gearmenu/commit/d3d9f94f63fc14f2b3f07d10a0707ddfaae4e5d3. I will probably add more configuration options regarding the size of the slots in a future release. For now I just changed the size to a more appropriate size for Scale 1.0.

Cheers,
RagedUnicorn
