### ISSUE TITLE
Ranged Weapon Slot and Wands

### ISSUE THREAD

**Issue by BurnHavoc** [RagedUnicorn/wow-classic-gearmenu#20]
Can you double check functionality with the ranged slot and Wands? I have 2 wands I swap between for damage type resisting mobs, and I can't get the other wand to show up on mouseover.

**Comment by RagedUnicorn** [comment]
Hi @BurnHavoc,

Will try this out a bit. It could indeed be that there is an issue because when I last tested this it was on 'retail' and on retail there is no such thing as a ranged slot. Can you still explain a little bit more what you expect and what exactly happens. I'm not sure if I can follow your explanation in the ticket.

Cheers,
RagedUnicorn

**Comment by BurnHavoc** [comment]
Ahh yeah, using Classic client to replicate:

Have 2 different wands, one equipped and one in-bag. When you try to use gearmenu to switch between them (like main/offhand weapons), no options appear.

**Comment by RagedUnicorn** [comment]
Hi @BurnHavoc,

Now I understood what you meant. I only had a rogue with some bows to test and this worked without a problem. The issue was related to how Gearmenu searches for eligible items.

Gearmenu searched for `INVTYPE_RANGED` which essentially only includes bows and not other items such as wands, guns or crossbows. This is fixed in 1ad65c9c0c390a78e566954ef854db8c39aab162. I added both `INVTYPE_THROWN`which includes throw weapons and `INVTYPE_RANGEDRIGHT ` which includes Wands, Guns, and Crossbows.

This change will be included in the next release.

Cheers,
RagedUnicorn
