### ISSUE TITLE
Chat is spammed & cant set quick change rules

### ISSUE THREAD

**Issue by hardtofin** [RagedUnicorn/wow-classic-gearmenu#28]
hi there, great addon!

I have a couple of issues, firstly, whenever i hover over an item on my bar it prints a message in chat, so after a couple of seconds i see this:

GearMenu:ItemManager - Ignoring item because its quality is lower than setting 2 
GearMenu:ItemManager - Ignoring item because its quality is lower than setting 2 
GearMenu:ItemManager - Ignoring item because its quality is lower than setting 2 
GearMenu:ItemManager - Ignoring item because its quality is lower than setting 2 
GearMenu:ItemManager - Ignoring item because its quality is lower than setting 2 
GearMenu:Ticker - Stopped 'ChangeMenuTicker'

Secondly, I can't set a quick change rule.  Both the top box and the left hand box are totally blank with only something available in the right hand box.  I read through the instructions on the mian page but i cant see how to get this quick change rule to work.

Many thanks!

EDIT:  It's like it's in verbose mode, it prints to chat nearly every action it does.  This was from just hovering over the buttons left to right:

GearMenu:Ticker - Started 'ChangeMenuTicker' 
GearMenu:ItemManager - Ignoring item because its quality is lower than setting 2 
GearMenu:ItemManager - Ignoring item because its quality is lower than setting 2 
GearMenu:ItemManager - Ignoring item because its quality is lower than setting 2 
GearMenu:ItemManager - Ignoring item because its quality is lower than setting 2 
GearMenu:Ticker - Stopped 'ChangeMenuTicker' 
GearMenu:Ticker - Started 'ChangeMenuTicker' 
GearMenu:ItemManager - Ignoring item because its quality is lower than setting 2 
GearMenu:ItemManager - Ignoring item because its quality is lower than setting 2 
GearMenu:ItemManager - Ignoring item because its quality is lower than setting 2 
GearMenu:ItemManager - Ignoring item because its quality is lower than setting 2 
GearMenu:ItemManager - Ignoring item because its quality is lower than setting 2 
GearMenu:Ticker - Stopped 'ChangeMenuTicker' 
GearMenu:Ticker - Started 'ChangeMenuTicker' 
GearMenu:ItemManager - Ignoring item because its quality is lower than setting 2 
GearMenu:ItemManager - Ignoring item because its quality is lower than setting 2 
GearMenu:ItemManager - Ignoring item because its quality is lower than setting 2 
GearMenu:ItemManager - Ignoring item because its quality is lower than setting 2 
GearMenu:ItemManager - Ignoring item because its quality is lower than setting 2 
GearMenu:ItemManager - Ignoring item because its quality is lower than setting 2 
GearMenu:ItemManager - Ignoring item because its quality is lower than setting 2 
GearMenu:ItemManager - Ignoring item because its quality is lower than setting 2 
GearMenu:ItemManager - Ignoring item because its quality is lower than setting 2 
GearMenu:ItemManager - Ignoring item because its quality is lower than setting 2 
GearMenu:Ticker - Stopped 'ChangeMenuTicker'

**Comment by RagedUnicorn** [comment]
Hi @hardtofin,

The first issue you can easily solve by downloading a release instead of the development version.

You can find the releases here: https://github.com/RagedUnicorn/wow-classic-gearmenu/releases

For the second issue you need to make sure that you have an item in that category that has an onuse effect.

On the left side you choose an item that is considered to be tracked when it is used. On the right side you choose an item that is switched to if the left item triggers the quickchange rule.

As an example if you choose the category trinket and you have an item such as https://classic.wowhead.com/item=2820/nifty-stopwatch

This trinket has an onuse effect and thus shows up in the left side as a possible item for a switch. On the right side all the items of the same category (trinket) are eligible to be switched to. They don't need to have an onuse effect.

Hope that helps. If not feel free to ask more questions.

Cheers,
Ragedunicorn
