### ISSUE TITLE
No releases in release page

### ISSUE THREAD

**Issue by lebongael** [RagedUnicorn/wow-classic-gearmenu#3]
Hi, I can't seem to find any releases to download on the releases page, is this normal ? Should we use the vanilla version for now ? 
![image](https://user-images.githubusercontent.com/16318676/63876334-93fbbe00-c9c5-11e9-97d7-7b2a3390e4e3.png)

**Comment by RagedUnicorn** [comment]
Hi That is because there is no release yet. Besides some UI Issues I think the current version should work but I have yet to test it. I wasn't in the beta and had no way to test so far. Once I hit 60 I should have time to fix the last minor bugs that I know about and do a first release.

The vanilla version will unfortunately not work at all. This addon is almost a complete rewrite.

Cheers,
RagedUnicorn

**Comment by lebongael** [comment]
Alright, thanks for the quick reply, have fun leveling ! I'll be testing this version and will report if I find any bugs.

**Comment by RagedUnicorn** [comment]
Not a problem. Make sure to do the following otherwise the debug messages will clutter your chat window.

This means however that interested people with some technical understanding can already download the master branch of the addon (name the folder GearMenu) and change some basic values in the GM_Environment.lua file (to stop the debug log spam).

Copy and overwrite the content of the file with the following:

RGGM_ENVIRONMENT = {
  ADDON_IDENTIFIER = "com.ragedunicorn.wow.classic.gearmenu-addon",
  LOG_LEVEL = 1,
  LOG_EVENT = false,
  DEBUG = false
}

**Comment by ktaragorn** [comment]
If you add it to the readme it should be ready :D 

I found this via https://classic.wowhead.com/guides/warrior-tank-addons-classic-wow#gear-swapping-addon so you might have others coming too. Let me test it as well. I think worst case you should create a 0.0.1 release just with what you have

**Comment by RagedUnicorn** [comment]
Hi Guys,

First release is finaly out. Find it here - https://github.com/RagedUnicorn/wow-classic-gearmenu/releases

Cheers,
RagedUnicorn
