### ISSUE TITLE
Gnomish Cloaking Device not showing

### ISSUE THREAD

**Issue by rafaelpimpa** [RagedUnicorn/wow-classic-gearmenu#30]
[Gnomish Cloaking Device](https://classic.wowhead.com/item=4397/gnomish-cloaking-device) is not showing when hovering.

**Comment by RagedUnicorn** [comment]
Hi @rafaelpimpa 

I don't have access to a cloaking device myself. But the issue that you see is probably because of the filter that is set on items. In the addon settings you can change the quality that an item has to have before it is picked up by Gearmenu and shown as a possible item to switch to. Because the gnomish cloaking device is white in quality it is getting filtered.

Cheers,
RagedUnicorn

**Comment by jakeswork** [comment]
Was just about to raise this for [Gnomish Net-o-matic Projector](https://classic.wowhead.com/item=10720/gnomish-net-o-matic-projector). Same mistake! 😄
