### ISSUE TITLE
Integrating ItemRack-like Features

### ISSUE THREAD

**Issue by phendrome** [RagedUnicorn/wow-classic-gearmenu#39]
This addon is great. But it serves a purpose of doing what ItemRack and TrinketMenu does combined, but it misses some really important features from them which would be lovely to have:

- Being able to swap items in the character panel (by clicking on your chest you'll see other available chests, etc)
- Being able to save different sets and bind them (for example, changing boots, gloves and trinket for mount speed with one button -- and using same button to change back)

More of a cosmetic feature I'd love is changing the skin of the bars (using the default Blizzard art) or at least having the option for it. Unless it's easy to tweak yourself? See the screenshot below anyway, you'd understand why I'd prefer it (and probably ton of other people just wanting the more Blizz-like feeling too it.

![WoWScrnShot_112519_065744](https://user-images.githubusercontent.com/2565750/69798312-621b1300-11d1-11ea-96cc-8425430e0e06.jpg)

**Comment by RagedUnicorn** [comment]
Hi @phendrome 

My goal wasn't to combine what Itemrack and Trinketmenu do. I rather wanted a more modern version of TrinketMenu and one that supports other slots as well back when I played on Nostalrius.

The main feature in my opinion is the combatqueue that helps switch items whenever possible. I'm torn between adding "itemset" functionality to the addon because I think there are already other addons that give you that ability and it was never a goal that I had in mind with the addon.

I understand that some people like the classic look and others love a more modern look. I will see if theres an easy way to change the "skin" of the addon.

Cheers,
RagedUnicorn

**Comment by phendrome** [comment]
From that perspective I definitely understand what you mean and the goal of the addon.

From the other perspective it would be that you can skip using TrinketMenu, but you'll still have to use ItemRack to get the other functionality, while you can "sort of" half-do (like swapping mount boots & trinket), but it takes longer than pressing a button like with ItemRack (or the old, better Outfitter, which was amazing). 

Anyway, what I'm trying to say is that it's so close to replace old ItemRack already, a modern one would be fucking amazing. Perhaps skipping the character panel idea, but being able to save sets, then you can skip ItemRack completely which is a mess of an addon.

**A usage scenario:** You use all 17 slots for all your gear for your GearMenu. You can save that particular setup of chosen items and it'll "queue them up in combat" to change them with a keybind. That'd solve it no? 

The gear setups are up to the user, smaller, bigger.

Perhaps an easier solution that goes well with the current addon then adding the character panel and all that.

Anyway, YES to the Blizzard art option. Would be SICK.

**Comment by phendrome** [comment]
> Anyway, YES to the Blizzard art option. Would be SICK.
Any update regarding this? Literally the only thing that's missing.

**Comment by Vequis-uk** [comment]
This addon was exactly what I was looking for, an option to have a "classic/ blizz" style and the ability to space the buttons out would make this addon absolutely perfect!

I was looking for something like ItemRack but in a toolbar format and this works great!

Also if it would be possible to modify how the list presents itself, as it would be nice to have all items on one column.

Really appreciate any consideration, keep up the great work! :)

**Comment by alexriedl** [comment]
As a hunter I switch trinkets a lot during boss fights. Different boss fights require a different set of trinkets to be used, based on fight length, creature type (Undead/Beast/Humanoid), ect. 

Having different sets control different queues would be extremely useful and align with the goal of the addon AFAICT

**Comment by phendrome** [comment]
Recently got back to SoM and... love this addon... b-b-but. I do miss one thing when it comes to this addon.

... the visual changes? More specifically a default Blizzard art option? When?! <3

**Comment by RagedUnicorn** [comment]
Hi @phendrome 

Started working on this yesterday. Was way more work than I anticipated it to be.

Here is an example how it currently looks. I'm not really an expert at WoW UIs and it is definitely not a perfect match to the default Blizzard option but I think this is as good as it gets currently. I mostly dealt with the issue that icons already have a border(sometimes) and other have ugly(gressil) artifacts. Because of that the icons are slightly zoomed in the classic version. Will check later if there is a better option.

Let me know what you think.

Custom (current)
![custom](https://user-images.githubusercontent.com/26184132/146801200-3d3bf86a-fa8a-4513-a425-f847aec80024.png)

Classic
![classic](https://user-images.githubusercontent.com/26184132/146801214-438bf61e-caea-4ed2-b882-da5b88a59b94.png)

There is still quite a bit work to do:
* Adapt the changeMenu to the same style
* Adapt the trinketMenu to the same style
* Add addon option to change theme (reload of interface required)

Cheers,
RagedUnicorn

**Comment by phendrome** [comment]
That is awesome @RagedUnicorn -- thank you a lot for this! 

Overall I think it's good. Perhaps not pixel perfect like you've mentioned and the fact that they're slightly zoomed in right.

Perhaps you've not had this thought yet, but potentially being able to introduce button spacing as well between the icons -- if you want to follow the more Blizzard style type of theming.

**Comment by RagedUnicorn** [comment]
Closing this theme was implemented a couple release ago
