### ISSUE TITLE
Queueing while casting doesn't function

### ISSUE THREAD

**Issue by Olorun** [RagedUnicorn/wow-classic-gearmenu#40]
When I am casting (even non-combat) I can queue up a trinket swap, but it won't swap the trinket after the cast is finished. Example: While I'm summoning my mount (3 second cast), and trying to swap from trinket A to the carrot on a stick. The carrot on a stick gets added to the queue, as shown by the smaller icon on the currently equipped trinket slot in gearmenu. Once the cast is finished, the carrot on a stick stays queue'd up, and doesn't get equipped.

**Comment by RagedUnicorn** [comment]
Hi @Olorun 

Just wanted to mention that I saw this behavior happen from time to time. I was able to track down the issue and fixed it.

The fix was commited here https://github.com/RagedUnicorn/wow-classic-gearmenu/commit/923796e3e5dd8275dba6e46b4573dfcad2ffafac

This fix will be included in the next release.
