### ISSUE TITLE
Countdown numbers are not shown

### ISSUE THREAD

**Issue by KevinTyrrell** [RagedUnicorn/wow-classic-gearmenu#43]
Switching trinkets or items correctly shows a dial fade for the 30 second cooldown until the item is ready. However cooldown numbers on the buttons themselves are missing. Is this normal? Is another addon needed for that functionality? Is there an option I may have missed?

**Comment by KevinTyrrell** [comment]
Strange -- They seem to be present now, but I haven't made changes. I can't tell if ElvUI is interfering or not.

**Comment by RagedUnicorn** [comment]
Hi @KevinTyrrell 

I saw that issue as well but quite rare. Because of that I was not yet able to reproduce and actually figure out what happened there. I'm using the standard blizzard behavior there for the timers.

If you figure out anything else or how to reproduce the issue please let me know.

Cheers,
Michael
