### ISSUE TITLE
[Suggestion] Show GearMenu on Mouseover

### ISSUE THREAD

**Issue by heyiamsven** [RagedUnicorn/wow-classic-gearmenu#63]
Hello,

first of all I love Gearmenu, but I have a very minimalistic UI and I want to show Gearmenu only when I hover over GearMenu's Bar with my mouse. Is this possible to receive this feature?

Thankyou in advance!

**Comment by RagedUnicorn** [comment]
Hi @heyiamsven 

Sadly not really in a viable way. The thing is that all those slots are secure action buttons in blizzards ui interface. Secure in this case means it is restricted what one can do with them especially during combat. It is not possible to move, hide or show such buttons during combat. This would make the feature pointless in my opinion because once combat starts you would not be able to see your gearmenu. The addon however specifically aims to help the player during combat.

Cheers,
RagedUnicorn
