### ISSUE TITLE
Cannot choose 1h weapon in offhand when dual wield spec

### ISSUE THREAD

**Issue by NordikaMan** [RagedUnicorn/wow-classic-gearmenu#88]

**Comment by NordikaMan** [comment]
![image](https://user-images.githubusercontent.com/9384449/143307440-820ac5e8-ef49-40a5-aa6f-44bf4ad5d3d9.png)
![image](https://user-images.githubusercontent.com/9384449/143307456-df26e1c0-d63b-4b41-87b6-d5f1e58ea3f9.png)

**Comment by NordikaMan** [comment]
![image](https://user-images.githubusercontent.com/9384449/143307499-c2d1c7f0-cc3f-4d21-951d-3f465a069a05.png)

**Comment by RagedUnicorn** [comment]
Hi @NordikaMan 

I wasn't able to reproduce this. I had other people mentioning a similar behavior but all of them turned out to be an issue with the item filtering. It would help to have a full screenshot so I can see what item seems to be the problem.

Also please make sure that the item is not filtered by the itemQuality filter.

Cheers,
RagedUnicorn

**Comment by RagedUnicorn** [comment]
Closing this because it is a very old ticket with no reproducable bug
